alias python=python3
alias py=python3
alias g=git
alias gs="git status"
alias gc="git commit -m"
alias gp="git push"
alias gd="git diff"
alias gf="git fetch"
alias gaa="git add -A"
alias lsa="ls -lha"
alias venv="source venv/bin/activate"
alias ..="cd .."
