alias python=python3
alias py=python3
alias g=git
alias gs="git status"
alias ga= "git add"
alias gc="git commit -m"
alias gp="git push"
alias gd="git diff"
alias lsa="ls -lha"
alias venv="source venv/bin/activate"
alias ..="cd .."
